sudo: required

language: go

services:
- docker

go:
- 1.11.2

install: true

script:
- make
- docker login 

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

deploy:
  - provider: script
    script: make deploy
    on:
      branch: master
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: iAOygEZ6pxvNGJ8iKZBVL/eqnrQBx92neBFSGQPG8wtqbGBq23xqegbLqiammHhCD2Kal6ekEwox17a0yKNCwyOIWcc3nuXbu7RP2vlnwOnFLiH1WsFGv9O8ELISVHS9c1EPVGhYBOeCd3gVcLoO2917uzFNF/JaLOjqxqSfYEHyU1i0T0VBPE7v1yV8TVv2PW86H5jLij9c+xMevHPsKyWTClRhQlMH5RChOihz1QanZ/b1AxRf+UlAtMdWTNKge3kVtIZXn1Vsjso+iI3poLdnm7kS5opRNOZcy+kEE9jtAxD1gBRj3Hgi7YkpMXwG4FeHjXpw11Mm4Sr74zljvpc31KSzaLsWyq+Abew8UcPBocxvI1UUdZA4ulkgv9vKR7fARmN0zM65tTk9TZM/woglLuGhri5qAvARQjxRJVySuMSUoJH80s/bcDHmUf/vY1ZpB/pwXzhzyUWiahrMuvH+m//ylZ42TGJPkRVswTRE3O3OeR7RDxJxD8y4iHpkicmndRzmbZ9Wn6I/GLEfYwhBHHb0a8ncpUrFth8z3tCVPs1j138CG+cB/Jz1OlQdE5ABj1BM/1TrXyn1fXPhvr3FVtVR7n3+QiIipvfIQcOpnLzkM4PpTFFhwke7Jd641ZIPw1SlX1kEA+bf77lufmjRLyuYUUUsMV7kr68rSsc=
    file: "$TRAVIS_BUILD_DIR/virtual-ip"
    on:
      tags: true
      repo: darxkies/virtual-ip
      branch: travis
